services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/build/docker/Dockerfile
    image: broker-service
    container_name: broker-service
    volumes:
      - ./../broker-service/config:/usr/local/bin/config
    environment:
      - CONFIG_PATH=/usr/local/bin/config/config.yaml
    restart: always
    ports:
      - "4000:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres-service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - messageflow

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/build/docker/Dockerfile
    image: auth-service
    container_name: auth-service
    volumes:
      - ./../auth-service/config:/usr/local/bin/config
    environment:
      - CONFIG_PATH=/usr/local/bin/config/config.yaml
    restart: always
    ports:
      - "4001:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres-service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - messageflow

  postgres-service:
    image: postgres:16-alpine
    container_name: postgres-service
    ports:
      - "5433:5432" #psql -h localhost -p 5433 -U postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/messageflow
    volumes:
      - messageflow:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - messageflow

#-------------------------------------------------------------------------------

  elasticsearch:
    image: elasticsearch:9.1.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - messageflow

  kibana:
    image: kibana:9.1.3
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - messageflow

  vector:
    image: timberio/vector:0.49.0-debian
    container_name: vector
    user: root
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - elasticsearch
    networks:
      - messageflow

#-------------------------------------------------------------------------------

volumes:
  messageflow:
  esdata:

networks:
  messageflow:
