services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/build/docker/Dockerfile
    image: broker-service
    container_name: broker-service
    volumes:
      - ./../broker-service/config:/usr/local/bin/config
    environment:
      - CONFIG_PATH=/usr/local/bin/config/config.yaml
    restart: always
    ports:
      - "4000:4000"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5433:5432" #psql -h localhost -p 5433 -U postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/messageflow
    volumes:
      - messageflow:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  messageflow:
